#!/bin/sh /etc/rc.common

. /lib/blue-merle/functions.sh

# We intend to be started before the first network-related service is started.
# According to https://openwrt.org/docs/techref/initscripts, /etc/rc.d/ determines
# the order of the services to be started (or stopped). The lower the number,
# the earlier the service is started.
# We observe "repeater" having the value 15. "network" 20. We certainly want to ahead of those.
START=10
STOP=99

start() {
	if ! APPLY_CONFIGURED_MACS; then
		logger -p notice -t blue-merle-init "Falling back to random MACs"
		RESET_BSSIDS
		RANDOMIZE_MACADDR
	fi
}
